export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DISABLE_LOGIN = 'DISABLE_LOGIN';
export const ENABLE_LOGIN = 'ENABLE_LOGIN';
export const FILL_PASSWORD = 'FILL_PASSWORD';
export const FILL_USERNAME = 'FILL_USERNAME';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const VALIDATE_FORM = 'VALIDATE_FORM';
